declare module 'uikit-react' {
  export const Accordion: React.ComponentType<AccordionProps>
  export const AccordionItem: React.ComponentType<AccordionItemProps>
  export const Alert: React.ComponentType<AlertProps>
  export const Article: React.ComponentType<ArticleProps>
  export const Badge: React.ComponentType<BadgeProps>
  export const Breadcrumb: React.ComponentType<BreadcrumbProps>
  export const Button: React.ComponentType<ButtonProps>
  export const Card: React.ComponentType<CardProps>
  export const CardBody: React.ComponentType<BaseProps>
  export const CardFooter: React.ComponentType<BaseProps>
  export const CardHeader: React.ComponentType<BaseProps>
  export const CardTitle: React.ComponentType<BaseProps>
  export const Container: React.ComponentType<ContainerProps>
  export const Cover: React.ComponentType<CoverProps>
  export const Dark: React.ComponentType<BaseProps>
  export const Dropdown: React.ComponentType<DropdownProps>
  export const Flex: React.ComponentType<FlexProps>
  export const Checkbox: React.ComponentType<FormInputProps>
  export const Fieldset: React.ComponentType<BaseProps>
  export const Form: React.ComponentType<FormProps>
  export const Input: React.ComponentType<FormInputProps>
  export const InputContainer: React.ComponentType<BaseContainerProps>
  export const FormLabel: React.ComponentType<BaseProps>
  export const Legend: React.ComponentType<BaseProps>
  export const Radio: React.ComponentType<FormInputProps>
  export const Range: React.ComponentType<FormInputProps>
  export const Select: React.ComponentType<FormSelectProps>
  export const SelectOption: React.ComponentType<React.HTMLProps<HTMLOptionElement>>
  export const Textarea: React.ComponentType<FormTextareaProps>
  export const Grid: React.ComponentType<GridProps>
  export const Icon: React.ComponentType<IconProps>
  export const Image: React.ComponentType<ImageProps>
  export const Label: React.ComponentType<LabelProps>
  export const Light: React.ComponentType<BaseProps>
  export const Lightbox: React.ComponentType<LightboxProps>
  export const LightboxItem: React.ComponentType<LightboxItemProps>
  export const Link: React.ComponentType<LinkProps>
  export const List: React.ComponentType<ListProps>
  export const ListItem: React.ComponentType<BaseProps>
  export const Margin: React.ComponentType<MarginProps>
  export const Nav: React.ComponentType<NavProps>
  export const NavItem: React.ComponentType<NavItemProps>
  export const Navbar: React.ComponentType<NavbarProps>
  export const NavbarContainer: React.ComponentType<NavbarContainerProps>
  export const NavbarDropdown: React.ComponentType<BaseProps>
  export const NavbarSticky: React.ComponentType<NavbarStickyProps>
  export const Offcanvas: React.ComponentType<OffcanvasProps>
  export const OffcanvasContainer: React.ComponentType<BaseProps>
  export const Overlay: React.ComponentType<OverlayProps>
  export const Panel: React.ComponentType<PanelProps>
  export const Parallax: React.ComponentType<ParallaxProps>
  export const Progress: React.ComponentType<ProgressProps>
  export const Scrollspy: React.ComponentType<ScrollspyProps>
  export const Section: React.ComponentType<SectionProps>
  export const Sidebar: React.ComponentType<SidebarProps>
  export const Slideshow: React.ComponentType<SlideshowProps>
  export const Tab: React.ComponentType<BaseProps>
  export const TabContainer: React.ComponentType<TabContainerProps>
  export const TabContent: React.ComponentType<BaseProps>
  export const Table: React.ComponentType<TableProps>
  export const TableBody: React.ComponentType<BaseProps>
  export const TableData: React.ComponentType<BaseProps>
  export const TableFoot: React.ComponentType<BaseProps>
  export const TableHead: React.ComponentType<BaseProps>
  export const TableHeader: React.ComponentType<BaseProps>
  export const TableRow: React.ComponentType<BaseProps>
}
